const host = "britishhomeinterior.co.uk";
const key = "9595dbbe694c4c258d2ff56465dac2f7";
const keyLocation = `https://${host}/${key}.txt`;

// urlList is regenerated by scripts/ship-new-posts.mjs — do not hand-edit.
const urlList = [
  "https://britishhomeinterior.co.uk/",
  "https://britishhomeinterior.co.uk/about/",
  "https://britishhomeinterior.co.uk/author/",
  "https://britishhomeinterior.co.uk/contact/",
  "https://britishhomeinterior.co.uk/editorial-policy/",
  "https://britishhomeinterior.co.uk/privacy-policy/",
  "https://britishhomeinterior.co.uk/terms-of-use/",
  "https://britishhomeinterior.co.uk/blog/",
  "https://britishhomeinterior.co.uk/blog/bedroom-colour-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/budget-kitchen-cabinet-makeover-uk/",
  "https://britishhomeinterior.co.uk/blog/budget-kitchen-splashback-tile-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/damp-mould-renters-guide-uk/",
  "https://britishhomeinterior.co.uk/blog/deposit-deductions-uk/",
  "https://britishhomeinterior.co.uk/blog/electric-prepayment-meter-rented-flat-uk/",
  "https://britishhomeinterior.co.uk/blog/first-time-renter-flat-setup-checklist-uk/",
  "https://britishhomeinterior.co.uk/blog/galley-kitchen-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/hallway-decor-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/kitchen-on-a-budget-uk/",
  "https://britishhomeinterior.co.uk/blog/living-room-colour-schemes-uk/",
  "https://britishhomeinterior.co.uk/blog/peel-and-stick-wallpaper-test-uk/",
  "https://britishhomeinterior.co.uk/blog/rental-kitchen-upgrade-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/rented-flat-makeover-uk/",
  "https://britishhomeinterior.co.uk/blog/renter-friendly-bedroom-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/renter-friendly-living-room-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/renter-friendly-living-room-layout-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/small-bathroom-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/small-bedroom-budget-uk/",
  "https://britishhomeinterior.co.uk/blog/small-bedroom-layout-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/small-box-room-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/small-living-room-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/small-living-room-layout-ideas/",
  "https://britishhomeinterior.co.uk/blog/studio-flat-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/terraced-house-hallway-ideas-uk/",
  "https://britishhomeinterior.co.uk/blog/utility-room-ideas-uk/",
];

async function main() {
  const res = await fetch("https://api.indexnow.org/indexnow", {
    method: "POST",
    headers: { "Content-Type": "application/json; charset=utf-8" },
    body: JSON.stringify({ host, key, keyLocation, urlList }),
  });
  console.log("Status:", res.status);
  console.log(await res.text());
}

main();
